//! Shared theme and font configuration for IntelliBoard UI
//! 
//! Provides the "Japan 2046" cyberpunk aesthetic used across all UI components.

use eframe::egui;
use log::info;

// Japan 2046 Palette (Cyber-Japonism)
pub const BG_COLOR: egui::Color32 = egui::Color32::from_rgb(10, 10, 16);      // Deep Cyber Night
pub const PANEL_COLOR: egui::Color32 = egui::Color32::from_rgb(15, 15, 20);   // Slightly lighter
pub const NEON_CYAN: egui::Color32 = egui::Color32::from_rgb(0, 243, 255);    // Cyber Cyan
pub const NEON_PINK: egui::Color32 = egui::Color32::from_rgb(255, 0, 60);     // Cyber Pink
pub const TEXT_COLOR: egui::Color32 = egui::Color32::from_rgb(220, 230, 255); // Cool White
pub const INACTIVE_BG: egui::Color32 = egui::Color32::from_rgb(25, 25, 35);
pub const HOVERED_BG: egui::Color32 = egui::Color32::from_rgb(35, 35, 50);

// Edge colors for memory graph
pub const EDGE_ACTION: egui::Color32 = egui::Color32::from_rgb(0, 200, 255);      // Blue - action result
pub const EDGE_PROMOTION: egui::Color32 = egui::Color32::from_rgb(0, 255, 100);   // Green - promotion
pub const EDGE_USER: egui::Color32 = egui::Color32::from_rgb(255, 200, 0);        // Yellow - user-created
pub const EDGE_FORMAT: egui::Color32 = egui::Color32::from_rgb(255, 128, 0);      // Orange - format

// Embedded icon data (generated by build.rs, fallback to programmatic generation)
const ICON_SIZE: u32 = 64;

/// Load the app icon as RGBA bytes (for tray and window icons)
/// Returns (rgba_bytes, width, height)
pub fn load_icon_rgba() -> (Vec<u8>, u32, u32) {
    // Try multiple locations for the icon
    let paths_to_try = [
        // Relative to current directory
        std::path::PathBuf::from("resources/icon.png"),
        // Relative to executable
        std::env::current_exe()
            .ok()
            .and_then(|p| p.parent().map(|d| d.join("resources/icon.png")))
            .unwrap_or_default(),
        // Config directory (same as config files)
        std::env::current_exe()
            .ok()
            .and_then(|p| p.parent().map(|d| d.join("config/../resources/icon.png")))
            .unwrap_or_default(),
    ];
    
    for path in &paths_to_try {
        if path.exists() {
            if let Ok(img) = image::open(path) {
                let rgba = img.to_rgba8();
                let (w, h) = rgba.dimensions();
                return (rgba.into_raw(), w, h);
            }
        }
    }
    
    // Fallback: generate vibrant calligraphy horse programmatically
    generate_calligraphy_horse_icon()
}

/// Generate a HEROIC rearing horse icon programmatically (fallback)
/// Thin detailed strokes with white-to-cyan gradient
fn generate_calligraphy_horse_icon() -> (Vec<u8>, u32, u32) {
    let size = ICON_SIZE;
    let mut rgba = vec![0u8; (size * size * 4) as usize];
    
    // Helper to draw thin stroke with white-cyan gradient
    let draw_stroke = |rgba: &mut [u8], x0: f32, y0: f32, x1: f32, y1: f32, width: f32, color_t: f32| {
        // Gradient: pure white (1.0) to electric cyan (0.0)
        let white = (255.0f32, 255.0f32, 255.0f32);
        let cyan = (0.0f32, 230.0f32, 255.0f32);
        let r = (cyan.0 + (white.0 - cyan.0) * color_t) as u8;
        let g = (cyan.1 + (white.1 - cyan.1) * color_t) as u8;
        let b = (cyan.2 + (white.2 - cyan.2) * color_t) as u8;
        
        let steps = ((x1 - x0).abs().max((y1 - y0).abs()) * 4.0) as i32 + 1;
        for i in 0..=steps {
            let t = i as f32 / steps as f32;
            let cx = x0 + (x1 - x0) * t;
            let cy = y0 + (y1 - y0) * t;
            let w = width * (0.7 + 0.4 * (t * std::f32::consts::PI).sin());
            
            for dy in (-(w as i32) - 1)..=(w as i32 + 1) {
                for dx in (-(w as i32) - 1)..=(w as i32 + 1) {
                    let px = (cx + dx as f32) as i32;
                    let py = (cy + dy as f32) as i32;
                    if px >= 0 && px < size as i32 && py >= 0 && py < size as i32 {
                        let dist = ((dx as f32).powi(2) + (dy as f32).powi(2)).sqrt();
                        if dist <= w {
                            let alpha = if dist > w - 0.8 { ((w - dist) / 0.8 * 255.0).min(255.0) as u8 } else { 255 };
                            let idx = ((py as u32 * size + px as u32) * 4) as usize;
                            let old_a = rgba[idx + 3] as u32;
                            let new_a = alpha as u32;
                            let out_a = old_a + new_a - (old_a * new_a / 255);
                            if out_a > 0 {
                                let blend = new_a as f32 / out_a as f32;
                                rgba[idx] = ((rgba[idx] as f32 * (1.0 - blend) + r as f32 * blend)) as u8;
                                rgba[idx + 1] = ((rgba[idx + 1] as f32 * (1.0 - blend) + g as f32 * blend)) as u8;
                                rgba[idx + 2] = ((rgba[idx + 2] as f32 * (1.0 - blend) + b as f32 * blend)) as u8;
                                rgba[idx + 3] = out_a.min(255) as u8;
                            }
                        }
                    }
                }
            }
        }
    };
    
    // HEROIC REARING HORSE - thin detailed strokes, white-cyan gradient
    
    // Back hooves (cyan)
    draw_stroke(&mut rgba, 42.0, 60.0, 44.0, 62.0, 1.0, 0.15);
    draw_stroke(&mut rgba, 54.0, 58.0, 56.0, 62.0, 1.0, 0.1);
    
    // Back legs
    draw_stroke(&mut rgba, 42.0, 48.0, 42.0, 60.0, 1.4, 0.2);
    draw_stroke(&mut rgba, 44.0, 40.0, 42.0, 48.0, 1.5, 0.25);
    draw_stroke(&mut rgba, 52.0, 46.0, 54.0, 58.0, 1.3, 0.15);
    draw_stroke(&mut rgba, 50.0, 38.0, 52.0, 46.0, 1.4, 0.2);
    
    // Hindquarters
    draw_stroke(&mut rgba, 48.0, 36.0, 54.0, 32.0, 1.8, 0.25);
    draw_stroke(&mut rgba, 46.0, 38.0, 50.0, 36.0, 1.6, 0.3);
    
    // Tail
    draw_stroke(&mut rgba, 54.0, 32.0, 58.0, 26.0, 1.2, 0.1);
    draw_stroke(&mut rgba, 58.0, 26.0, 60.0, 18.0, 1.0, 0.05);
    draw_stroke(&mut rgba, 60.0, 18.0, 58.0, 10.0, 0.8, 0.0);
    draw_stroke(&mut rgba, 58.0, 10.0, 54.0, 4.0, 0.7, 0.0);
    draw_stroke(&mut rgba, 56.0, 28.0, 60.0, 22.0, 0.9, 0.08);
    draw_stroke(&mut rgba, 60.0, 22.0, 62.0, 14.0, 0.8, 0.02);
    draw_stroke(&mut rgba, 62.0, 14.0, 60.0, 6.0, 0.7, 0.0);
    draw_stroke(&mut rgba, 58.0, 24.0, 62.0, 18.0, 0.8, 0.05);
    draw_stroke(&mut rgba, 62.0, 18.0, 64.0, 10.0, 0.6, 0.0);
    
    // Body
    draw_stroke(&mut rgba, 48.0, 36.0, 40.0, 30.0, 2.0, 0.35);
    draw_stroke(&mut rgba, 40.0, 30.0, 32.0, 24.0, 1.9, 0.45);
    draw_stroke(&mut rgba, 36.0, 32.0, 46.0, 38.0, 1.8, 0.35);
    draw_stroke(&mut rgba, 34.0, 28.0, 42.0, 34.0, 1.6, 0.4);
    
    // Chest
    draw_stroke(&mut rgba, 32.0, 24.0, 28.0, 28.0, 1.8, 0.55);
    draw_stroke(&mut rgba, 28.0, 28.0, 26.0, 34.0, 1.6, 0.6);
    
    // Front legs RAISED
    draw_stroke(&mut rgba, 26.0, 34.0, 20.0, 40.0, 1.4, 0.65);
    draw_stroke(&mut rgba, 20.0, 40.0, 12.0, 42.0, 1.2, 0.7);
    draw_stroke(&mut rgba, 12.0, 42.0, 6.0, 38.0, 1.0, 0.75);
    draw_stroke(&mut rgba, 6.0, 38.0, 4.0, 34.0, 0.8, 0.8);
    draw_stroke(&mut rgba, 28.0, 30.0, 32.0, 38.0, 1.3, 0.6);
    draw_stroke(&mut rgba, 32.0, 38.0, 28.0, 46.0, 1.1, 0.65);
    draw_stroke(&mut rgba, 28.0, 46.0, 22.0, 44.0, 0.9, 0.7);
    
    // Neck
    draw_stroke(&mut rgba, 32.0, 24.0, 28.0, 18.0, 1.7, 0.6);
    draw_stroke(&mut rgba, 28.0, 18.0, 26.0, 12.0, 1.6, 0.7);
    draw_stroke(&mut rgba, 26.0, 12.0, 28.0, 8.0, 1.5, 0.8);
    draw_stroke(&mut rgba, 30.0, 20.0, 28.0, 14.0, 1.4, 0.65);
    
    // Head
    draw_stroke(&mut rgba, 28.0, 8.0, 32.0, 6.0, 1.4, 0.85);
    draw_stroke(&mut rgba, 32.0, 6.0, 38.0, 8.0, 1.2, 0.9);
    draw_stroke(&mut rgba, 38.0, 8.0, 42.0, 10.0, 1.0, 0.95);
    draw_stroke(&mut rgba, 42.0, 10.0, 44.0, 12.0, 0.8, 1.0);
    draw_stroke(&mut rgba, 30.0, 10.0, 36.0, 12.0, 0.9, 0.88);
    draw_stroke(&mut rgba, 34.0, 8.0, 35.0, 9.0, 0.6, 0.0);
    draw_stroke(&mut rgba, 43.0, 11.0, 44.0, 12.0, 0.5, 0.0);
    
    // Ears
    draw_stroke(&mut rgba, 28.0, 8.0, 24.0, 2.0, 0.9, 0.9);
    draw_stroke(&mut rgba, 24.0, 2.0, 26.0, 4.0, 0.7, 0.85);
    draw_stroke(&mut rgba, 30.0, 6.0, 28.0, 0.0, 0.8, 0.92);
    draw_stroke(&mut rgba, 28.0, 0.0, 30.0, 2.0, 0.6, 0.88);
    
    // Mane
    draw_stroke(&mut rgba, 26.0, 14.0, 18.0, 8.0, 1.0, 0.5);
    draw_stroke(&mut rgba, 18.0, 8.0, 10.0, 6.0, 0.8, 0.3);
    draw_stroke(&mut rgba, 10.0, 6.0, 4.0, 8.0, 0.6, 0.1);
    draw_stroke(&mut rgba, 24.0, 16.0, 14.0, 12.0, 1.1, 0.45);
    draw_stroke(&mut rgba, 14.0, 12.0, 6.0, 12.0, 0.9, 0.2);
    draw_stroke(&mut rgba, 6.0, 12.0, 2.0, 16.0, 0.7, 0.05);
    draw_stroke(&mut rgba, 22.0, 18.0, 12.0, 16.0, 1.0, 0.4);
    draw_stroke(&mut rgba, 12.0, 16.0, 4.0, 18.0, 0.8, 0.15);
    draw_stroke(&mut rgba, 28.0, 12.0, 20.0, 6.0, 0.9, 0.55);
    draw_stroke(&mut rgba, 20.0, 6.0, 12.0, 4.0, 0.7, 0.25);
    draw_stroke(&mut rgba, 30.0, 10.0, 24.0, 4.0, 0.8, 0.6);
    draw_stroke(&mut rgba, 24.0, 4.0, 16.0, 2.0, 0.6, 0.2);
    draw_stroke(&mut rgba, 20.0, 20.0, 8.0, 20.0, 0.9, 0.35);
    draw_stroke(&mut rgba, 8.0, 20.0, 2.0, 24.0, 0.7, 0.1);
    draw_stroke(&mut rgba, 18.0, 22.0, 6.0, 24.0, 0.8, 0.25);
    draw_stroke(&mut rgba, 6.0, 24.0, 2.0, 28.0, 0.6, 0.05);
    
    (rgba, size, size)
}

/// Apply greyscale filter to RGBA data (for inactive state)
pub fn apply_greyscale(rgba: &mut [u8]) {
    for chunk in rgba.chunks_exact_mut(4) {
        let grey = ((chunk[0] as u32 + chunk[1] as u32 + chunk[2] as u32) / 3) as u8;
        chunk[0] = grey;
        chunk[1] = grey;
        chunk[2] = grey;
        // Keep alpha unchanged
    }
}

/// Create tray icon from RGBA data
pub fn rgba_to_tray_icon(rgba: Vec<u8>, width: u32, height: u32) -> tray_icon::Icon {
    tray_icon::Icon::from_rgba(rgba, width, height).expect("Failed to create tray icon")
}

/// Create egui IconData from RGBA data (for window icons)
pub fn rgba_to_egui_icon(rgba: Vec<u8>, width: u32, height: u32) -> egui::IconData {
    egui::IconData {
        rgba,
        width,
        height,
    }
}

/// Load icon for egui window (convenience function)
pub fn load_egui_icon() -> egui::IconData {
    let (rgba, w, h) = load_icon_rgba();
    rgba_to_egui_icon(rgba, w, h)
}

/// Load active tray icon
pub fn load_tray_icon_active() -> tray_icon::Icon {
    let (rgba, w, h) = load_icon_rgba();
    rgba_to_tray_icon(rgba, w, h)
}

/// Load inactive (greyscale) tray icon
pub fn load_tray_icon_inactive() -> tray_icon::Icon {
    let (mut rgba, w, h) = load_icon_rgba();
    apply_greyscale(&mut rgba);
    rgba_to_tray_icon(rgba, w, h)
}

/// Apply the Japan 2046 cyberpunk theme to an egui context
pub fn apply_theme(ctx: &egui::Context) {
    let mut visuals = egui::Visuals::dark();

    visuals.panel_fill = PANEL_COLOR;
    visuals.window_fill = BG_COLOR;
    visuals.override_text_color = Some(TEXT_COLOR);
    
    // Selection
    visuals.selection.bg_fill = NEON_PINK;
    visuals.selection.stroke = egui::Stroke::new(1.0, egui::Color32::WHITE);
    
    // Widgets
    visuals.widgets.noninteractive.bg_fill = PANEL_COLOR;
    visuals.widgets.noninteractive.fg_stroke = egui::Stroke::new(1.0, NEON_CYAN);
    
    visuals.widgets.inactive.bg_fill = INACTIVE_BG;
    visuals.widgets.hovered.bg_fill = HOVERED_BG;
    visuals.widgets.active.bg_fill = NEON_CYAN;
    visuals.widgets.active.fg_stroke = egui::Stroke::new(1.0, egui::Color32::BLACK);
    
    ctx.set_visuals(visuals);
}

/// Configure CJK fonts for proper Chinese/Japanese/Korean text rendering
pub fn configure_fonts(ctx: &egui::Context) {
    let mut fonts = egui::FontDefinitions::default();
    
    // Cross-platform font search list
    let font_candidates = [
        // Windows
        "c:\\Windows\\Fonts\\msyh.ttc",    // Microsoft YaHei
        "c:\\Windows\\Fonts\\simhei.ttf",   // SimHei
        "c:\\Windows\\Fonts\\msgothic.ttc", // MS Gothic
        // macOS
        "/System/Library/Fonts/PingFang.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
        // Linux
        "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    ];
    
    for path in font_candidates {
        if let Ok(font_data) = std::fs::read(path) {
            fonts.font_data.insert(
                "cjk_font".to_owned(),
                egui::FontData::from_owned(font_data),
            );

            // Put CJK font first (highest priority) for proportional text
            fonts.families
                .entry(egui::FontFamily::Proportional)
                .or_default()
                .insert(0, "cjk_font".to_owned());

            // Put CJK font as last fallback for monospace
            fonts.families
                .entry(egui::FontFamily::Monospace)
                .or_default()
                .push("cjk_font".to_owned());

            ctx.set_fonts(fonts);
            info!("Loaded CJK font from {}", path);
            return;
        }
    }
    log::warn!("Failed to load any CJK fonts. Characters may not display correctly.");
}
